Word embedding Techniques using embedding layer of keras

In [3]:
#need tensorflow 2.0 or above and keras

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
##sentences
sent = [
    'This is mango',
    'This is Orange',
    'cup of tea',
    'This is my hometown',
    'old is gold'
]

In [5]:
sent

['This is mango',
 'This is Orange',
 'cup of tea',
 'This is my hometown',
 'old is gold']

In [6]:
#first param for one-hot
voc_size = 1000

One hot representation

In [8]:
onehot_rep = [one_hot(words,voc_size) for words in sent]

In [9]:
print(onehot_rep)

[[188, 344, 421], [188, 344, 184], [721, 688, 424], [188, 344, 525, 28], [931, 344, 278]]


Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [13]:
sent_length = 8
embeded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)
print(embeded_docs)

[[  0   0   0   0   0 188 344 421]
 [  0   0   0   0   0 188 344 184]
 [  0   0   0   0   0 721 688 424]
 [  0   0   0   0 188 344 525  28]
 [  0   0   0   0   0 931 344 278]]


In [14]:
dim = 15

In [15]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             10000     
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embeded_docs))

[[[ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429
   -0.00560316 -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
  [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429
   -0.00560316 -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
  [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429
   -0.00560316 -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
  [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429
   -0.00560316 -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
  [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429
   -0.00560316 -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
  [-0.03431346 -0.0343046   0.04012758 -0.02178118 -0.01995126
    0.04494802  0.03958212  0.03034756  0.03578501 -0.0350629 ]
  [ 0.00358815  0.01282325 -0.03052311 -0.02556847 -0.01439849
    0.00774335  0.00093111 -0.04057572  0.02160758 -0.02342591]
  [ 0.04580568  0.04533758  0.02532667 -0.02239834  0.00373526
   -0.02173383  0.04559671  0.02752734 -0.006919

In [18]:
print(embeded_docs[0])

[  0   0   0   0   0 188 344 421]


In [20]:
print(model.predict(embeded_docs)[0])

[[ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429 -0.00560316
  -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
 [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429 -0.00560316
  -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
 [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429 -0.00560316
  -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
 [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429 -0.00560316
  -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
 [ 0.03046833 -0.02391632  0.00127598 -0.01551467  0.02498429 -0.00560316
  -0.04597951 -0.01246854 -0.03783388  0.0492484 ]
 [-0.03431346 -0.0343046   0.04012758 -0.02178118 -0.01995126  0.04494802
   0.03958212  0.03034756  0.03578501 -0.0350629 ]
 [ 0.00358815  0.01282325 -0.03052311 -0.02556847 -0.01439849  0.00774335
   0.00093111 -0.04057572  0.02160758 -0.02342591]
 [ 0.04580568  0.04533758  0.02532667 -0.02239834  0.00373526 -0.02173383
   0.04559671  0.02752734 -0.00691909 -0.04613851]]