In [38]:
import pandas as pd
import numpy as np

In [39]:
df_1 = pd.read_csv('datasets/exports/data1.csv')
df_2 = pd.read_csv('datasets/exports/df_2018.csv')
df_3 = pd.read_csv('datasets/exports/df_2019.csv')
df_4 = pd.read_csv('datasets/exports/df_2020.csv')
df_5 = pd.read_csv('datasets/exports/df_2021.csv')

In [40]:
df_1.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon-Levitt   
4        Doug Walker      Doug Walker        Rob Walker               unknown   

                            genres  \
0  Action Adventure Fantasy Sci-Fi   
1         Action Adventure Fantasy   
2        Action Adventure Thriller   
3                  Action Thriller   
4                      Documentary   

                                         movie_title  
0                                             avatar  
1           pirates of the caribbean: at world's end  
2                                            spectre  
3                              the dark knight rises  
4  star wars: episode vii - the force awakens    ...

In [41]:
df_1 = df_1.rename(columns={'genres':'Genres'})

In [42]:
df_1['comb'] = df_1['actor_1_name'] + ' ' + df_1['actor_2_name'] + ' '+ df_1['actor_3_name'] + ' '+ df_1['director_name'] +' ' + df_1['Genres']

In [44]:
df = (((df_1.append(df_2,ignore_index=True)).append(df_3,ignore_index=True)).append(df_4,ignore_index=True)).append(df_5,ignore_index=True)

In [45]:
df.isna().sum()

director_name    106
actor_1_name       0
actor_2_name       0
actor_3_name       0
Genres             0
movie_title        0
comb             104
dtype: int64

In [46]:
df = df.fillna('unknown')

In [112]:
df.drop_duplicates(subset=['movie_title'],inplace=True)

In [113]:
df

director_name        actor_1_name       actor_2_name  \
0         James Cameron         CCH Pounder   Joel David Moore   
1        Gore Verbinski         Johnny Depp      Orlando Bloom   
2            Sam Mendes     Christoph Waltz       Rory Kinnear   
3     Christopher Nolan           Tom Hardy     Christian Bale   
4           Doug Walker         Doug Walker         Rob Walker   
...                 ...                 ...                ...   
6143     Matthew Vaughn       Ralph Fiennes     Gemma Arterton   
6144          Joel Coen   Denzel Washington  Frances McDormand   
6145  Denzel Washington   Michael B. Jordan       Chanté Adams   
6146     Erwin brothers        Zachary Levi        Anna Paquin   
6147         Joe Wright      Peter Dinklage      Haley Bennett   

              actor_3_name                           Genres  \
0                Wes Studi  Action Adventure Fantasy Sci-Fi   
1           Jack Davenport         Action Adventure Fantasy   
2         Stephanie Sigman        Action Adventure Thriller   
3     Joseph Gordon-Levitt                  Action Thriller   
4                  unknown                      Documentary   
...                    ...                              ...   
6143            Rhys Ifans    War Action Thriller Adventure   
6144         Corey Hawkins                        Drama War   
6145               unknown                     Drama Comedy   
6146          Dennis Quaid                            Drama   
6147   Kelvin Harrison Jr.              Music Drama Romance   

                                            movie_title  \
0                                                avatar   
1              pirates of the caribbean: at world's end   
2                                               spectre   
3                                 the dark knight rises   
4     star wars: episode vii - the force awakens    ...   
...                                                 ...   
6143                                     the king's man   
6144                             the tragedy of macbeth   
6145                               a journal for jordan   
6146           american underdog: the kurt warner story   
6147                                             cyrano   

                                                   comb  
0     CCH Pounder Joel David Moore Wes Studi James C...  
1     Johnny Depp Orlando Bloom Jack Davenport Gore ...  
2     Christoph Waltz Rory Kinnear Stephanie Sigman ...  
3     Tom Hardy Christian Bale Joseph Gordon-Levitt ...  
4     Doug Walker Rob Walker unknown Doug Walker Doc...  
...                                                 ...  
6143   Ralph Fiennes Gemma Arterton Rhys Ifans Matth...  
6144   Denzel Washington Frances McDormand Corey Haw...  
6145   Michael B. Jordan Chanté Adams unknown Denzel...  
6146   Zachary Levi Anna Paquin Dennis Quaid Erwin b...  
6147   Peter Dinklage Haley Bennett Kelvin Harrison ...  

[5985 rows x 7 columns]

In [114]:
df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
Genres           0
movie_title      0
comb             0
dtype: int64

In [115]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon-Levitt   
4        Doug Walker      Doug Walker        Rob Walker               unknown   

                            Genres  \
0  Action Adventure Fantasy Sci-Fi   
1         Action Adventure Fantasy   
2        Action Adventure Thriller   
3                  Action Thriller   
4                      Documentary   

                                         movie_title  \
0                                             avatar   
1           pirates of the caribbean: at world's end   
2                                            spectre   
3                              the dark knight rises   
4  star wars: episode vii - the force awakens    ...   

                                                comb  
0  CCH Pounder Joel David Moore Wes Studi James C...  
1  Johnny Depp Orlando Bloom Jack Davenport Gore ...  
2  Christoph Waltz Rory Kinnear Stephanie Sigman ...  
3  Tom Hardy Christian Bale Joseph Gordon-Levitt ...  
4  Doug Walker Rob Walker unknown Doug Walker Doc...

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Extracting Features

In [117]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["comb"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [118]:
cosine_sim = cosine_similarity(count_matrix)

In [127]:
movie_user_likes = "spectre"
def get_index_from_title(title):
    return df[df.movie_title == title].index.values[0]

movie_index = get_index_from_title(movie_user_likes)

In [128]:
movie_index

2

In [129]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

In [130]:
similar_movies

[(0, 0.16116459280507606),
 (1, 0.18181818181818182),
 (2, 1.0000000000000002),
 (3, 0.18181818181818182),
 (4, 0.0),
 (5, 0.17407765595569785),
 (6, 0.2860387767736777),
 (7, 0.08058229640253803),
 (8, 0.16724840200141816),
 (9, 0.08703882797784893),
 (10, 0.17407765595569785),
 (11, 0.17407765595569785),
 (12, 0.38138503569823695),
 (13, 0.18181818181818182),
 (14, 0.18181818181818182),
 (15, 0.16724840200141816),
 (16, 0.17407765595569785),
 (17, 0.16724840200141816),
 (18, 0.2727272727272727),
 (19, 0.1556997888323046),
 (20, 0.09534625892455924),
 (21, 0.18181818181818182),
 (22, 0.16116459280507606),
 (23, 0.09534625892455924),
 (24, 0.08703882797784893),
 (25, 0.17407765595569785),
 (26, 0.0),
 (27, 0.16724840200141816),
 (28, 0.2508726030021272),
 (29, 0.24174688920761409),
 (30, 0.6363636363636365),
 (31, 0.2727272727272727),
 (32, 0.16724840200141816),
 (33, 0.09090909090909091),
 (34, 0.24174688920761409),
 (35, 0.08362420100070908),
 (36, 0.17407765595569785),
 (37, 0.17407

In [131]:
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

In [132]:
def get_title_from_index(index):
    return df[df.index == index]["movie_title"].values[0]
i=0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

spectre
skyfall
quantum of solace
the legend of tarzan
the meg
gods of egypt
the perfection
insurgent
hillbilly elegy
spider-man 3
the village
the santa clause 2
disclosure
all the pretty horses
indiana jones and the temple of doom
the andromeda strain
